all: ex00 ex01 ex02

ex00:
	make -C ex00/
	./ex00/megaphone

ex01:
	make -C ex01/
	./ex00/boocrap

ex02:
	make -C ex02/

clear:
	make fclean -C ex00/
	make fclean -C ex01/
	make fclean -C ex02/

.PHONY: all ex00 ex01 ex02
