all: ex00 ex01 ex02

ex00:
	make -C ex00/

ex01:
	make -C ex01/

ex02:
	make -C ex02/

test00:
	make test -C ex00/

test01:
	make test -C ex01/

test02:
	make test -C ex02/

clear:
	make fclean -C ex00/
	make fclean -C ex01/
	make fclean -C ex02/

.PHONY: all ex00 ex01 ex02
